parcelRequire=function(e,r,n,t){var i="function"==typeof parcelRequire&&parcelRequire,o="function"==typeof require&&require;function u(n,t){if(!r[n]){if(!e[n]){var f="function"==typeof parcelRequire&&parcelRequire;if(!t&&f)return f(n,!0);if(i)return i(n,!0);if(o&&"string"==typeof n)return o(n);var c=new Error("Cannot find module '"+n+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[n][1][r]||r};var l=r[n]=new u.Module(n);e[n][0].call(l.exports,p,l,l.exports,this)}return r[n].exports;function p(e){return u(p.resolve(e))}}u.isParcelRequire=!0,u.Module=function(e){this.id=e,this.bundle=u,this.exports={}},u.modules=e,u.cache=r,u.parent=i,u.register=function(r,n){e[r]=[function(e,r){r.exports=n},{}]};for(var f=0;f<n.length;f++)u(n[f]);if(n.length){var c=u(n[n.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=c:"function"==typeof define&&define.amd?define(function(){return c}):t&&(this[t]=c)}return u}({"bhRG":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});class e{constructor(e=/<<(.+)>>/u,t="[field]"){this.flag=e,this.defaultCssSelector=t}matchFlag(e){const t=e.match(this.flag);return t?t[1]:null}replaceFlag(e,t="\n"){return e.replace(this.flag,t)}everyNthLineBreak(e,t=0){const r=this.replaceFlag(e,"").trim().split(/\r\n|\r|\n/gu),l=[];let s=!1,a=0,c=0;return r.map(e=>{let r=!1;const n=""===e;l[a]||(l[a]=""),n?c++:c=0,r=c===t&&0!==t,l[a]+=`${e}\r\n`,r||(s=!1),r&&!s&&(a++,s=!0)}),0===t?l[0]:l}}exports.default=e;
},{}],"6Nue":[function(require,module,exports) {

},{}],"iHh7":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});const t=exports.mapObj=((t,e)=>{const s={};let a=0;for(const c in t)s[c]=e(t[c],c,a++);return s}),e=exports.fetchFiles=(t=>Object.keys(t).map(async e=>({name:`${e}.txt`,data:await fetch(t[e]).then(t=>t.text())})));
},{}],"vfZe":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=require("marked"),t=r(e);function r(e){return e&&e.__esModule?e:{default:e}}class s{constructor(e){if("string"!=typeof e)throw new Error(`constructor got ${typeof e} instead of string`);this._string=e}string(){return this._string}removePTag(){return new s(this._string.replace(/<p>/gu,"").replace(/<\/p>/gu,""))}removeComments(){return new s(this._string.replace(/\{\{[^]*\}\}/gu,""))}markdown(){return new s((0,t.default)(this._string))}_replaceMarkClasses(...e){const{3:t}=e;this._string=t;const r=e[2]?e[2].split(" "):null,s=Boolean(e[1])?"div":"span";return this.makeElement(s,r)}markClasses(){const e=this._string.replace(/(!?)\{([^{}]+)*\}(\S+)/gu,this._replaceMarkClasses.bind(this));return new s(e)}makeElement(e,t,r=null){const s=t?t.join(" "):null;return`<${e} ${r?`id="${r}"`:""} ${s?`class="${s}"`:""}>${this._string}</${e}>`}}exports.default=s;
},{}],"HY/A":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),require("../styles/dynamic-files.css");var e=require("./helpers"),t=require("./StringFormatter"),r=a(t),s=require("./FileFormatter"),i=a(s);function a(e){return e&&e.__esModule?e:{default:e}}class n extends i.default{constructor(e){super(e.flag,e.defaultCssSelector);const t=e.triggers&&e.triggers.default?e.triggers.default:null;this.triggers=this._bindThisToTriggers(e.triggers),this.triggers.default=this._renderDefault(this.defaultCssSelector,t).bind(this)}render(e){const t=new r.default(e.data);e.data=t.removeComments().string();const s=this.matchFlag(e.data);return s?this._emitTrigger(s,e):this._emitTrigger("default",e)}_emitTrigger(e,t,...r){if("default"===e)return this.triggers.default(t,...r);const s=`[${t.name.match(/(.+).txt/u)[1]}]`,i=Array.from(document.querySelectorAll(s)).map(e=>(this._displayFileNameToggle(t.name,e),e)),a=this.triggers[e];return a?a(t,i,...r):null}renderFatherChildren(e,t,s){t.map((t,i)=>{s.map((a,n)=>{Array.from(t.querySelectorAll(a)).map((t,a)=>{const l=a*s.length,d=n+l,o=(e[0].constructor===Array?new r.default(e[i][d]):new r.default(e[d])).markClasses().markdown().removePTag().string();t.innerHTML=o})})})}_renderDefault(e,t){const s=Array.from(document.querySelectorAll(e));let i=0;return t&&t(s),e=>{const t=s[i++],a=new r.default(e.data).removeComments().markClasses().markdown().string();t.innerHTML=a,this._displayFileNameToggle(e.name,t)}}_bindThisToTriggers(t){return(0,e.mapObj)(t,e=>e.bind(this))}_displayFileNameToggle(e,t){const r=document.createElement("div");r.classList.add("show-file-name"),r.innerHTML=e,t.classList.add("dynamic"),t.insertBefore(r,t.firstChild);const s=this._onDynamicFieldClick(r,2);let i=!1;window.addEventListener("keyup",e=>{"z"===e.key&&(i=!1)}),window.addEventListener("keydown",e=>{"z"===e.key&&(i=!0)}),t.addEventListener("click",e=>{i&&s(e)}),r.addEventListener("click",s)}_onDynamicFieldClick(e,t=3){let r=!1;return s=>{s.detail<t||(s.stopPropagation(),(r=!r)?e.classList.add("active"):e.classList.remove("active"))}}}exports.default=n;
},{"../styles/dynamic-files.css":"6Nue","./helpers":"iHh7","./StringFormatter":"vfZe","./FileFormatter":"bhRG"}],"3U5J":[function(require,module,exports) {
module.exports={FileFormatter:require("./FileFormatter.js"),FileRenderer:require("./FileRenderer.js"),helpers:require("./helpers.js"),StringFormatter:require("./StringFormatter.js")};
},{"./FileFormatter.js":"bhRG","./FileRenderer.js":"HY/A","./helpers.js":"iHh7","./StringFormatter.js":"vfZe"}],"G21N":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var e=require("./js/**.js");Object.keys(e).forEach(function(r){"default"!==r&&"__esModule"!==r&&Object.defineProperty(exports,r,{enumerable:!0,get:function(){return e[r]}})});
},{"./js/**.js":"3U5J"}]},{},["G21N"], null)
//# sourceMappingURL=barrel.map